# Generated by Django 3.0.5 on 2020-04-15 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='UserFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_username', models.CharField(max_length=50, verbose_name='FriendUsername')),
                ('friend_password', models.CharField(max_length=50, verbose_name='FriendPassword')),
                ('changes', models.CharField(max_length=10, verbose_name='Changes')),
                ('whose_friend_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.User')),
            ],
        ),
    ]
