# Generated by Django 3.0.5 on 2020-04-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userfriend',
            options={'verbose_name': 'Друг пользователя', 'verbose_name_plural': 'Друзья пользователей'},
        ),
        migrations.RemoveField(
            model_name='userfriend',
            name='changes',
        ),
    ]
